//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Entity
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.Data.Entity.ModelConfiguration;
	using System.ComponentModel.DataAnnotations.Schema;
	//using AWEFramework.AWEExtensions;
	using FbcBookIt.Utility;
	using System.Collections.Generic;
	
	// Table Name: BookRequest
	public partial class BookRequest: BASE_Entity
	{
		// Primary Keys
		public System.Guid BookRequestId { get; set; }
	
		// Non-Primary columns
		// Foreign Key to FormatType
		public System.Guid FormatTypeId { get; set; }
		public System.DateTime? RequestDate { get; set; }
		// Foreign Key to RequestStatu
		public System.Int32? RequestStatusId { get; set; }
		// Foreign Key to StudentTeacherSchool
		public System.Guid StudentTeacherSchoolId { get; set; }
		// Foreign Key to Title
		public System.Guid TitleID { get; set; }
	
	}
	
	public class BookRequestMap: EntityTypeConfiguration<BookRequest>
	{
		public BookRequestMap()
		{
			// Map entity to table
			ToTable("BookRequest");
	
			// Map property to column
			Property(t => t.BookRequestId).HasColumnName("BookRequestId");
			Property(t => t.FormatTypeId).HasColumnName("FormatTypeId");
			Property(t => t.RequestDate).HasColumnName("RequestDate");
			Property(t => t.RequestStatusId).HasColumnName("RequestStatusId");
			Property(t => t.StudentTeacherSchoolId).HasColumnName("StudentTeacherSchoolId");
			Property(t => t.TitleID).HasColumnName("TitleID");
	
			// Primary Key
			HasKey(t => t.BookRequestId);
	
			// Additional property mappings
			Property(t => t.BookRequestId)
				.IsRequired();
	
			Property(t => t.FormatTypeId)
				.IsRequired();
	
			Property(t => t.StudentTeacherSchoolId)
				.IsRequired();
	
			Property(t => t.TitleID)
				.IsRequired();
	
	
		}
	}
	
	public static partial class BookRequestHelper
	{
		public static void AssignNewPK
			(this BookRequest aBookRequest)
		{
			aBookRequest.BookRequestId = Guid.NewGuid().CombGuid();
		}
	
		/// <summary> 
		/// This code is fragile in that is ASSUMES that integer primary keys ARE
		/// AUTO-INCREMENTING columns whose value is governed by the database 
		/// server and that Guid primary keys are NOT "computed" values but rather 
		/// those whose column value is set by the client and/or server in a 
		/// fashion NOT governed by the database server.
		/// </summary>
		public static bool IsNew
			(this BookRequest aBookRequest)
		{
			if (aBookRequest == null)
			{
				throw 
					new ArgumentNullException
						(
							"aBookRequest"
							, "Entity instance cannot be null!"
						);
			}
			bool vResult = 
				(aBookRequest.BookRequestId == Guid.Empty);
			return vResult;
		}
	
		public static void AssignTo
			(BookRequest aFrom, BookRequest aTo)
		{
			aTo.BookRequestId = aFrom.BookRequestId;
			aTo.FormatTypeId = aFrom.FormatTypeId;
			aTo.RequestDate = aFrom.RequestDate;
			aTo.RequestStatusId = aFrom.RequestStatusId;
			aTo.StudentTeacherSchoolId = aFrom.StudentTeacherSchoolId;
			aTo.TitleID = aFrom.TitleID;
		}
	
		public static void AssignToNoPrimaryKeys
			(BookRequest aFrom, BookRequest aTo)
		{
			aTo.FormatTypeId = aFrom.FormatTypeId;
			aTo.RequestDate = aFrom.RequestDate;
			aTo.RequestStatusId = aFrom.RequestStatusId;
			aTo.StudentTeacherSchoolId = aFrom.StudentTeacherSchoolId;
			aTo.TitleID = aFrom.TitleID;
		}
	
		public static void AssignToJustPrimaryKeys
			(BookRequest aFrom, BookRequest aTo)
		{
			aTo.BookRequestId = aFrom.BookRequestId;
		}
	
		public static void AssignFrom
			(this BookRequest aTo, BookRequest aFrom)
		{
			aTo.BookRequestId = aFrom.BookRequestId;
			aTo.FormatTypeId = aFrom.FormatTypeId;
			aTo.RequestDate = aFrom.RequestDate;
			aTo.RequestStatusId = aFrom.RequestStatusId;
			aTo.StudentTeacherSchoolId = aFrom.StudentTeacherSchoolId;
			aTo.TitleID = aFrom.TitleID;
		}
	
		public static void AssignFromNoPrimaryKeys
			(this BookRequest aTo, BookRequest aFrom)
		{
			aTo.FormatTypeId = aFrom.FormatTypeId;
			aTo.RequestDate = aFrom.RequestDate;
			aTo.RequestStatusId = aFrom.RequestStatusId;
			aTo.StudentTeacherSchoolId = aFrom.StudentTeacherSchoolId;
			aTo.TitleID = aFrom.TitleID;
		}
	
		public static void AssignFromJustPrimaryKeys
			(this BookRequest aTo, BookRequest aFrom)
		{
			aTo.BookRequestId = aFrom.BookRequestId;
		}
	
	}
}
