//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Entity
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.Data.Entity.ModelConfiguration;
	using System.ComponentModel.DataAnnotations.Schema;
	//using AWEFramework.AWEExtensions;
	using FbcBookIt.Utility;
	using System.Collections.Generic;
	
	// Table Name: CopyStatus
	public partial class CopyStatus: BASE_Entity
	{
		// Primary Keys
		public System.Int32 CopyStatusId { get; set; }
	
		// Non-Primary columns
		public System.String StatusDescription { get; set; }
	
	}
	
	public class CopyStatusMap: EntityTypeConfiguration<CopyStatus>
	{
		public CopyStatusMap()
		{
			// Map entity to table
			ToTable("CopyStatus");
	
			// Map property to column
			Property(t => t.CopyStatusId).HasColumnName("CopyStatusId");
			Property(t => t.StatusDescription).HasColumnName("StatusDescription");
	
			// Primary Key
			HasKey(t => t.CopyStatusId);
	
			// Additional property mappings
			Property(t => t.CopyStatusId)
				.IsRequired();
	
	
		}
	}
	
	public static partial class CopyStatusHelper
	{
		public static void AssignNewPK
			(this CopyStatus aCopyStatus)
		{
		}
	
		/// <summary> 
		/// This code is fragile in that is ASSUMES that integer primary keys ARE
		/// AUTO-INCREMENTING columns whose value is governed by the database 
		/// server and that Guid primary keys are NOT "computed" values but rather 
		/// those whose column value is set by the client and/or server in a 
		/// fashion NOT governed by the database server.
		/// </summary>
		public static bool IsNew
			(this CopyStatus aCopyStatus)
		{
			if (aCopyStatus == null)
			{
				throw 
					new ArgumentNullException
						(
							"aCopyStatus"
							, "Entity instance cannot be null!"
						);
			}
			bool vResult = 
				(aCopyStatus.CopyStatusId < 1);
			return vResult;
		}
	
		public static void AssignTo
			(CopyStatus aFrom, CopyStatus aTo)
		{
			aTo.CopyStatusId = aFrom.CopyStatusId;
			aTo.StatusDescription = aFrom.StatusDescription;
		}
	
		public static void AssignToNoPrimaryKeys
			(CopyStatus aFrom, CopyStatus aTo)
		{
			aTo.StatusDescription = aFrom.StatusDescription;
		}
	
		public static void AssignToJustPrimaryKeys
			(CopyStatus aFrom, CopyStatus aTo)
		{
			aTo.CopyStatusId = aFrom.CopyStatusId;
		}
	
		public static void AssignFrom
			(this CopyStatus aTo, CopyStatus aFrom)
		{
			aTo.CopyStatusId = aFrom.CopyStatusId;
			aTo.StatusDescription = aFrom.StatusDescription;
		}
	
		public static void AssignFromNoPrimaryKeys
			(this CopyStatus aTo, CopyStatus aFrom)
		{
			aTo.StatusDescription = aFrom.StatusDescription;
		}
	
		public static void AssignFromJustPrimaryKeys
			(this CopyStatus aTo, CopyStatus aFrom)
		{
			aTo.CopyStatusId = aFrom.CopyStatusId;
		}
	
	}
}
