//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Entity
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.Data.Entity.ModelConfiguration;
	using System.ComponentModel.DataAnnotations.Schema;
	//using AWEFramework.AWEExtensions;
	using FbcBookIt.Utility;
	using System.Collections.Generic;
	
	// Table Name: District
	public partial class District: BASE_Entity
	{
		// Primary Keys
		public System.Guid DistrictId { get; set; }
	
		// Non-Primary columns
		public System.Boolean Active { get; set; }
		public System.String DistrictName { get; set; }
	
	}
	
	public class DistrictMap: EntityTypeConfiguration<District>
	{
		public DistrictMap()
		{
			// Map entity to table
			ToTable("District");
	
			// Map property to column
			Property(t => t.Active).HasColumnName("Active");
			Property(t => t.DistrictId).HasColumnName("DistrictId");
			Property(t => t.DistrictName).HasColumnName("DistrictName");
	
			// Primary Key
			HasKey(t => t.DistrictId);
	
			// Additional property mappings
			Property(t => t.Active)
				.IsRequired();
	
			Property(t => t.DistrictId)
				.IsRequired();
	
			Property(t => t.DistrictName)
				.IsRequired();
	
	
		}
	}
	
	public static partial class DistrictHelper
	{
		public static void AssignNewPK
			(this District aDistrict)
		{
			aDistrict.DistrictId = Guid.NewGuid().CombGuid();
		}
	
		/// <summary> 
		/// This code is fragile in that is ASSUMES that integer primary keys ARE
		/// AUTO-INCREMENTING columns whose value is governed by the database 
		/// server and that Guid primary keys are NOT "computed" values but rather 
		/// those whose column value is set by the client and/or server in a 
		/// fashion NOT governed by the database server.
		/// </summary>
		public static bool IsNew
			(this District aDistrict)
		{
			if (aDistrict == null)
			{
				throw 
					new ArgumentNullException
						(
							"aDistrict"
							, "Entity instance cannot be null!"
						);
			}
			bool vResult = 
				(aDistrict.DistrictId == Guid.Empty);
			return vResult;
		}
	
		public static void AssignTo
			(District aFrom, District aTo)
		{
			aTo.Active = aFrom.Active;
			aTo.DistrictId = aFrom.DistrictId;
			aTo.DistrictName = aFrom.DistrictName;
		}
	
		public static void AssignToNoPrimaryKeys
			(District aFrom, District aTo)
		{
			aTo.Active = aFrom.Active;
			aTo.DistrictName = aFrom.DistrictName;
		}
	
		public static void AssignToJustPrimaryKeys
			(District aFrom, District aTo)
		{
			aTo.DistrictId = aFrom.DistrictId;
		}
	
		public static void AssignFrom
			(this District aTo, District aFrom)
		{
			aTo.Active = aFrom.Active;
			aTo.DistrictId = aFrom.DistrictId;
			aTo.DistrictName = aFrom.DistrictName;
		}
	
		public static void AssignFromNoPrimaryKeys
			(this District aTo, District aFrom)
		{
			aTo.Active = aFrom.Active;
			aTo.DistrictName = aFrom.DistrictName;
		}
	
		public static void AssignFromJustPrimaryKeys
			(this District aTo, District aFrom)
		{
			aTo.DistrictId = aFrom.DistrictId;
		}
	
	}
}
