//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Entity
{
	using System;
	
	// Config File path: C:\Users\Sam\Documents\Visual Studio 2013\Projects\FbcBookIt\Web
	// Local DbMetaData file spec: Not Set
	// Local Db (non-server) Storage Spec: C:\AWETools\JsonData\MetaData.meta
	// Server Db connection string: Not Set
	// Web Service Url: Not Set
	// Metadata key: DefaultMetaDataKey 
	// MetaDataKey value: 43a11c94-dabe-4eee-a662-a46901085221
	public abstract class BASE_Entity 
	{
	}
	
}

