//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Entity
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.Data.Entity.ModelConfiguration;
	using System.ComponentModel.DataAnnotations.Schema;
	//using AWEFramework.AWEExtensions;
	using FbcBookIt.Utility;
	using System.Collections.Generic;
	
	// Table Name: Teacher
	public partial class Teacher: BASE_Entity
	{
		// Primary Keys
		public System.Guid TeacherID { get; set; }
	
		// Non-Primary columns
		public System.Boolean Active { get; set; }
		public System.String City { get; set; }
		public System.String Email { get; set; }
		public System.String Name { get; set; }
		public System.String Phone { get; set; }
		public System.String State { get; set; }
		public System.String StreetAddress { get; set; }
		public System.String Title { get; set; }
		public System.String ZipPlus4 { get; set; }
	
	}
	
	public class TeacherMap: EntityTypeConfiguration<Teacher>
	{
		public TeacherMap()
		{
			// Map entity to table
			ToTable("Teacher");
	
			// Map property to column
			Property(t => t.Active).HasColumnName("Active");
			Property(t => t.City).HasColumnName("City");
			Property(t => t.Email).HasColumnName("Email");
			Property(t => t.Name).HasColumnName("Name");
			Property(t => t.Phone).HasColumnName("Phone");
			Property(t => t.State).HasColumnName("State");
			Property(t => t.StreetAddress).HasColumnName("StreetAddress");
			Property(t => t.TeacherID).HasColumnName("TeacherID");
			Property(t => t.Title).HasColumnName("Title");
			Property(t => t.ZipPlus4).HasColumnName("ZipPlus4");
	
			// Primary Key
			HasKey(t => t.TeacherID);
	
			// Additional property mappings
			Property(t => t.Active)
				.IsRequired();
	
			Property(t => t.Name)
				.IsRequired();
	
			Property(t => t.TeacherID)
				.IsRequired();
	
			Property(t => t.ZipPlus4)
				.IsFixedLength()
				.HasMaxLength(10);
	
	
		}
	}
	
	public static partial class TeacherHelper
	{
		public static void AssignNewPK
			(this Teacher aTeacher)
		{
			aTeacher.TeacherID = Guid.NewGuid().CombGuid();
		}
	
		/// <summary> 
		/// This code is fragile in that is ASSUMES that integer primary keys ARE
		/// AUTO-INCREMENTING columns whose value is governed by the database 
		/// server and that Guid primary keys are NOT "computed" values but rather 
		/// those whose column value is set by the client and/or server in a 
		/// fashion NOT governed by the database server.
		/// </summary>
		public static bool IsNew
			(this Teacher aTeacher)
		{
			if (aTeacher == null)
			{
				throw 
					new ArgumentNullException
						(
							"aTeacher"
							, "Entity instance cannot be null!"
						);
			}
			bool vResult = 
				(aTeacher.TeacherID == Guid.Empty);
			return vResult;
		}
	
		public static void AssignTo
			(Teacher aFrom, Teacher aTo)
		{
			aTo.Active = aFrom.Active;
			aTo.City = aFrom.City;
			aTo.Email = aFrom.Email;
			aTo.Name = aFrom.Name;
			aTo.Phone = aFrom.Phone;
			aTo.State = aFrom.State;
			aTo.StreetAddress = aFrom.StreetAddress;
			aTo.TeacherID = aFrom.TeacherID;
			aTo.Title = aFrom.Title;
			aTo.ZipPlus4 = aFrom.ZipPlus4;
		}
	
		public static void AssignToNoPrimaryKeys
			(Teacher aFrom, Teacher aTo)
		{
			aTo.Active = aFrom.Active;
			aTo.City = aFrom.City;
			aTo.Email = aFrom.Email;
			aTo.Name = aFrom.Name;
			aTo.Phone = aFrom.Phone;
			aTo.State = aFrom.State;
			aTo.StreetAddress = aFrom.StreetAddress;
			aTo.Title = aFrom.Title;
			aTo.ZipPlus4 = aFrom.ZipPlus4;
		}
	
		public static void AssignToJustPrimaryKeys
			(Teacher aFrom, Teacher aTo)
		{
			aTo.TeacherID = aFrom.TeacherID;
		}
	
		public static void AssignFrom
			(this Teacher aTo, Teacher aFrom)
		{
			aTo.Active = aFrom.Active;
			aTo.City = aFrom.City;
			aTo.Email = aFrom.Email;
			aTo.Name = aFrom.Name;
			aTo.Phone = aFrom.Phone;
			aTo.State = aFrom.State;
			aTo.StreetAddress = aFrom.StreetAddress;
			aTo.TeacherID = aFrom.TeacherID;
			aTo.Title = aFrom.Title;
			aTo.ZipPlus4 = aFrom.ZipPlus4;
		}
	
		public static void AssignFromNoPrimaryKeys
			(this Teacher aTo, Teacher aFrom)
		{
			aTo.Active = aFrom.Active;
			aTo.City = aFrom.City;
			aTo.Email = aFrom.Email;
			aTo.Name = aFrom.Name;
			aTo.Phone = aFrom.Phone;
			aTo.State = aFrom.State;
			aTo.StreetAddress = aFrom.StreetAddress;
			aTo.Title = aFrom.Title;
			aTo.ZipPlus4 = aFrom.ZipPlus4;
		}
	
		public static void AssignFromJustPrimaryKeys
			(this Teacher aTo, Teacher aFrom)
		{
			aTo.TeacherID = aFrom.TeacherID;
		}
	
	}
}
