//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Entity
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.Data.Entity.ModelConfiguration;
	using System.ComponentModel.DataAnnotations.Schema;
	//using AWEFramework.AWEExtensions;
	using FbcBookIt.Utility;
	using System.Collections.Generic;
	
	// Table Name: Title
	public partial class Title: BASE_Entity
	{
		// Primary Keys
		public System.Guid ID { get; set; }
	
		// Non-Primary columns
		public System.Boolean Active { get; set; }
		public System.String ISBN { get; set; }
		public System.String Name { get; set; }
	
	}
	
	public class TitleMap: EntityTypeConfiguration<Title>
	{
		public TitleMap()
		{
			// Map entity to table
			ToTable("Title");
	
			// Map property to column
			Property(t => t.Active).HasColumnName("Active");
			Property(t => t.ID).HasColumnName("ID");
			Property(t => t.ISBN).HasColumnName("ISBN");
			Property(t => t.Name).HasColumnName("Name");
	
			// Primary Key
			HasKey(t => t.ID);
	
			// Additional property mappings
			Property(t => t.Active)
				.IsRequired();
	
			Property(t => t.ID)
				.IsRequired();
	
			Property(t => t.ISBN)
				.IsRequired();
	
			Property(t => t.Name)
				.IsRequired();
	
	
		}
	}
	
	public static partial class TitleHelper
	{
		public static void AssignNewPK
			(this Title aTitle)
		{
			aTitle.ID = Guid.NewGuid().CombGuid();
		}
	
		/// <summary> 
		/// This code is fragile in that is ASSUMES that integer primary keys ARE
		/// AUTO-INCREMENTING columns whose value is governed by the database 
		/// server and that Guid primary keys are NOT "computed" values but rather 
		/// those whose column value is set by the client and/or server in a 
		/// fashion NOT governed by the database server.
		/// </summary>
		public static bool IsNew
			(this Title aTitle)
		{
			if (aTitle == null)
			{
				throw 
					new ArgumentNullException
						(
							"aTitle"
							, "Entity instance cannot be null!"
						);
			}
			bool vResult = 
				(aTitle.ID == Guid.Empty);
			return vResult;
		}
	
		public static void AssignTo
			(Title aFrom, Title aTo)
		{
			aTo.Active = aFrom.Active;
			aTo.ID = aFrom.ID;
			aTo.ISBN = aFrom.ISBN;
			aTo.Name = aFrom.Name;
		}
	
		public static void AssignToNoPrimaryKeys
			(Title aFrom, Title aTo)
		{
			aTo.Active = aFrom.Active;
			aTo.ISBN = aFrom.ISBN;
			aTo.Name = aFrom.Name;
		}
	
		public static void AssignToJustPrimaryKeys
			(Title aFrom, Title aTo)
		{
			aTo.ID = aFrom.ID;
		}
	
		public static void AssignFrom
			(this Title aTo, Title aFrom)
		{
			aTo.Active = aFrom.Active;
			aTo.ID = aFrom.ID;
			aTo.ISBN = aFrom.ISBN;
			aTo.Name = aFrom.Name;
		}
	
		public static void AssignFromNoPrimaryKeys
			(this Title aTo, Title aFrom)
		{
			aTo.Active = aFrom.Active;
			aTo.ISBN = aFrom.ISBN;
			aTo.Name = aFrom.Name;
		}
	
		public static void AssignFromJustPrimaryKeys
			(this Title aTo, Title aFrom)
		{
			aTo.ID = aFrom.ID;
		}
	
	}
}
