//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	//using AWEFramework.AWECmn;
	//using Entity;
	using FbcBookIt.DataAccess;
	using FbcBookIt.Entity;
	
	// Table Name: BookRequest
	public partial interface IBookRequestR
		: IBASE_RepositoryDbTable
	{
		bool Any();
	
		bool Exists(System.Guid aBookRequestId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		BookRequest Find(System.Guid aBookRequestId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		BookRequest Get(System.Guid aBookRequestId);
	
		List<BookRequest> GetAll();
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		BookRequest Add(BookRequest aBookRequest);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		void Insert(BookRequest aBookRequest);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		System.Guid InsertAndReturnPrimaryKey(BookRequest aBookRequest);
	
		void Update(BookRequest aBookRequest);
	
		void Delete(System.Guid aBookRequestId);
	
	}
	
	public partial class BookRequestR
		: BASE_RepositoryDbTable, IBookRequestR
	{
		public BookRequestR
			(IFbcBookItContext aDb): base(aDb)
		{
		}
	
		public bool Any()
		{
			bool vResult;
			vResult = _Db.BookRequestDb.Any();
			return vResult;
		}
	
		public bool Exists(System.Guid aBookRequestId)
		{
			bool vResult;
				vResult = _Db.BookRequestDb.Any(aRec => (aRec.BookRequestId == aBookRequestId));
			return vResult;
		}
	
		public BookRequest Find(System.Guid aBookRequestId)
		{
			BookRequest vResult;
			vResult = _Db.BookRequestDb.Single(aRec => (aRec.BookRequestId == aBookRequestId));
			return vResult;
		}
	
		public BookRequest Get(System.Guid aBookRequestId)
		{
			BookRequest vResult;
			vResult = _Db.BookRequestDb.FirstOrDefault(aRec => aRec.BookRequestId == aBookRequestId);
			return vResult;
		}
	
		public List<BookRequest> GetAll()
		{
			List<BookRequest> vResult;
			vResult = _Db.BookRequestDb.ToList();
			return vResult;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public BookRequest Add(BookRequest aBookRequest)
		{
			if (aBookRequest == null)
			{
				throw new ArgumentNullException("aBookRequest", " cannot be null!");
			}
	/*
			if (!aBookRequest.IsRootEntity())
			{
				aBookRequest.ClearToRootEntity();
			}
	*/
			if (!aBookRequest.IsNew())
			{
				const string MESSAGE = 
					"BookRequest Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
				aBookRequest.AssignNewPK();
			aBookRequest = _Db.BookRequestDb.Add(aBookRequest);
			_Db.SaveChanges();
			return aBookRequest;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public void Insert(BookRequest aBookRequest)
		{
			if (aBookRequest == null)
			{
				throw new ArgumentNullException("aBookRequest", " cannot be null!");
			}
	/*
			if (!aBookRequest.IsRootEntity())
			{
				aBookRequest.ClearToRootEntity();
			}
	*/
			if (!aBookRequest.IsNew())
			{
				const string MESSAGE = 
					"BookRequest Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aBookRequest.AssignNewPK();
			_Db.BookRequestDb.Add(aBookRequest);
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public System.Guid InsertAndReturnPrimaryKey(BookRequest aBookRequest)
		{
			if (aBookRequest == null)
			{
				throw new ArgumentNullException("aBookRequest", " cannot be null!");
			}
	/*
			if (!aBookRequest.IsRootEntity())
			{
				aBookRequest.ClearToRootEntity();
			}
	*/
			if (!aBookRequest.IsNew())
			{
				const string MESSAGE = 
					"BookRequest Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aBookRequest.AssignNewPK();
			aBookRequest = _Db.BookRequestDb.Add(aBookRequest);
			_Db.SaveChanges();
			System.Guid vResult = aBookRequest.BookRequestId;
			return vResult;
		}
	
		public void Update(BookRequest aBookRequest)
		{
			BookRequest vRec = 
				_Db.BookRequestDb.FirstOrDefault(aRec => aRec.BookRequestId == aBookRequest.BookRequestId);
			vRec.AssignFromNoPrimaryKeys(aBookRequest);
			_Db.SaveChanges();
		}
	
		public void Delete(System.Guid aBookRequestId)
		{
			BookRequest vRec = 
				_Db.BookRequestDb.FirstOrDefault(aRec => aRec.BookRequestId == aBookRequestId);
			if (vRec == null)
			{
				return; // Record is already gone, no worries!
			}
			_Db.BookRequestDb.Remove(vRec);
			_Db.SaveChanges();
		}
	
	}
}
