//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	//using AWEFramework.AWECmn;
	//using Entity;
	using FbcBookIt.DataAccess;
	using FbcBookIt.Entity;
	
	// Table Name: LoanStatus
	public partial interface ILoanStatusR
		: IBASE_RepositoryDbTable
	{
		bool Any();
	
		bool Exists(System.Int32 aLoanStatusId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		LoanStatus Find(System.Int32 aLoanStatusId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		LoanStatus Get(System.Int32 aLoanStatusId);
	
		List<LoanStatus> GetAll();
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		LoanStatus Add(LoanStatus aLoanStatus);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		void Insert(LoanStatus aLoanStatus);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		System.Int32 InsertAndReturnPrimaryKey(LoanStatus aLoanStatus);
	
		void Update(LoanStatus aLoanStatus);
	
		void Delete(System.Int32 aLoanStatusId);
	
		bool IsActive(System.Int32 aLoanStatusId);
	
		void Remove(System.Int32 aLoanStatusId);
	
		void Restore(System.Int32 aLoanStatusId);
	
		void DeleteAllRemoved();
	
	}
	
	public partial class LoanStatusR
		: BASE_RepositoryDbTable, ILoanStatusR
	{
		public LoanStatusR
			(IBookInventoryContext aDb): base(aDb)
		{
		}
	
		public bool Any()
		{
			bool vResult;
			vResult = _Db.LoanStatusDb.Any();
			return vResult;
		}
	
		public bool Exists(System.Int32 aLoanStatusId)
		{
			bool vResult;
				vResult = _Db.LoanStatusDb.Any(aRec => (aRec.LoanStatusId == aLoanStatusId));
			return vResult;
		}
	
		public LoanStatus Find(System.Int32 aLoanStatusId)
		{
			LoanStatus vResult;
			vResult = _Db.LoanStatusDb.Single(aRec => (aRec.LoanStatusId == aLoanStatusId));
			return vResult;
		}
	
		public LoanStatus Get(System.Int32 aLoanStatusId)
		{
			LoanStatus vResult;
			vResult = _Db.LoanStatusDb.FirstOrDefault(aRec => aRec.LoanStatusId == aLoanStatusId);
			return vResult;
		}
	
		public List<LoanStatus> GetAll()
		{
			List<LoanStatus> vResult;
			vResult = _Db.LoanStatusDb.ToList();
			return vResult;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public LoanStatus Add(LoanStatus aLoanStatus)
		{
			if (aLoanStatus == null)
			{
				throw new ArgumentNullException("aLoanStatus", " cannot be null!");
			}
	/*
			if (!aLoanStatus.IsRootEntity())
			{
				aLoanStatus.ClearToRootEntity();
			}
	*/
			if (!aLoanStatus.IsNew())
			{
				const string MESSAGE = 
					"LoanStatus Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
				aLoanStatus.AssignNewPK();
			aLoanStatus = _Db.LoanStatusDb.Add(aLoanStatus);
			_Db.SaveChanges();
			return aLoanStatus;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public void Insert(LoanStatus aLoanStatus)
		{
			if (aLoanStatus == null)
			{
				throw new ArgumentNullException("aLoanStatus", " cannot be null!");
			}
	/*
			if (!aLoanStatus.IsRootEntity())
			{
				aLoanStatus.ClearToRootEntity();
			}
	*/
			if (!aLoanStatus.IsNew())
			{
				const string MESSAGE = 
					"LoanStatus Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aLoanStatus.AssignNewPK();
			_Db.LoanStatusDb.Add(aLoanStatus);
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public System.Int32 InsertAndReturnPrimaryKey(LoanStatus aLoanStatus)
		{
			if (aLoanStatus == null)
			{
				throw new ArgumentNullException("aLoanStatus", " cannot be null!");
			}
	/*
			if (!aLoanStatus.IsRootEntity())
			{
				aLoanStatus.ClearToRootEntity();
			}
	*/
			if (!aLoanStatus.IsNew())
			{
				const string MESSAGE = 
					"LoanStatus Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aLoanStatus.AssignNewPK();
			aLoanStatus = _Db.LoanStatusDb.Add(aLoanStatus);
			_Db.SaveChanges();
			System.Int32 vResult = aLoanStatus.LoanStatusId;
			return vResult;
		}
	
		public void Update(LoanStatus aLoanStatus)
		{
			LoanStatus vRec = 
				_Db.LoanStatusDb.FirstOrDefault(aRec => aRec.LoanStatusId == aLoanStatus.LoanStatusId);
			vRec.AssignFromNoPrimaryKeys(aLoanStatus);
			_Db.SaveChanges();
		}
	
		public void Delete(System.Int32 aLoanStatusId)
		{
			LoanStatus vRec = 
				_Db.LoanStatusDb.FirstOrDefault(aRec => aRec.LoanStatusId == aLoanStatusId);
			if (vRec == null)
			{
				return; // Record is already gone, no worries!
			}
			_Db.LoanStatusDb.Remove(vRec);
			_Db.SaveChanges();
		}
	
		public bool IsActive(System.Int32 aLoanStatusId)
		{
			LoanStatus vRec = 
				_Db.LoanStatusDb.FirstOrDefault(aRec => aRec.LoanStatusId == aLoanStatusId);
			bool vResult = (vRec != null) && vRec.Active;
			return vResult;
		}
	
		public void Remove(System.Int32 aLoanStatusId)
		{
			LoanStatus vRec = 
				_Db.LoanStatusDb.FirstOrDefault(aRec => aRec.LoanStatusId == aLoanStatusId);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = false;
			_Db.SaveChanges();
		}
	
		public void Restore(System.Int32 aLoanStatusId)
		{
			LoanStatus vRec = 
				_Db.LoanStatusDb.FirstOrDefault(aRec => aRec.LoanStatusId == aLoanStatusId);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = true;
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Note that this method in EF is Really Ugly in that EF requires that 
		/// each record to be deleted must first be brought into the context, then 
		/// "removed", then SaveChanges called to actually delete the record(s).
		/// For a large number of records this gets memory intensive.
		/// </remark>
		public void DeleteAllRemoved()
		{
			List<LoanStatus> vToDelete =
				_Db.LoanStatusDb
					.Where(aRec => !aRec.Active).ToList();
			if (vToDelete.Count < 1)
			{
				return;
			}
			foreach (LoanStatus vRec in vToDelete)
			{
				_Db.LoanStatusDb.Remove(vRec);
			}
			_Db.SaveChanges();
		}
	
	}
}
