 
 
 
//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	//using Entity;
	using FbcBookIt.DataAccess;
	
	// BASE_Repository is a container for the context
	public partial interface IBASE_Repository
	{
	}
	
	public abstract partial class BASE_Repository: IBASE_Repository
	{
		protected readonly IFbcBookItContext _Db;
	
		protected BASE_Repository(IFbcBookItContext aDb)
		{
			if (aDb == null)
			{
				throw new ArgumentNullException("aDb");  
			}
			_Db = aDb;
		}
	
	}
	
	// Given that stored procs don't need anything other than a connection, they
	// are declared next
	public interface IBASE_RepositoryStoredProcs: IBASE_Repository
	{
	}
	
	public abstract partial class BASE_RepositoryStoredProcs
		: BASE_Repository, IBASE_RepositoryStoredProcs
	{
		protected BASE_RepositoryStoredProcs
			(IFbcBookItContext aDb): base(aDb)
		{
		}
	
	}
	
	// This repository is for tables and/or views
	public interface IBASE_RepositoryDbTable: IBASE_Repository
	{
	}
	
	public abstract partial class BASE_RepositoryDbTable
		: BASE_Repository, IBASE_RepositoryDbTable
	{
		protected BASE_RepositoryDbTable(IFbcBookItContext aDb)
			: base(aDb)
		{
		}
	}
	
}

