//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	//using AWEFramework.AWECmn;
	//using Entity;
	using FbcBookIt.DataAccess;
	using FbcBookIt.Entity;
	
	// Table Name: RequestStatus
	public partial interface IRequestStatusR
		: IBASE_RepositoryDbTable
	{
		bool Any();
	
		bool Exists(System.Int32 aRequestStatusId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		RequestStatu Find(System.Int32 aRequestStatusId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		RequestStatu Get(System.Int32 aRequestStatusId);
	
		List<RequestStatu> GetAll();
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		RequestStatu Add(RequestStatu aRequestStatu);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		void Insert(RequestStatu aRequestStatu);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		System.Int32 InsertAndReturnPrimaryKey(RequestStatu aRequestStatu);
	
		void Update(RequestStatu aRequestStatu);
	
		void Delete(System.Int32 aRequestStatusId);
	
	}
	
	public partial class RequestStatusR
		: BASE_RepositoryDbTable, IRequestStatusR
	{
		public RequestStatusR
			(IFbcBookItContext aDb): base(aDb)
		{
		}
	
		public bool Any()
		{
			bool vResult;
			vResult = _Db.RequestStatuDb.Any();
			return vResult;
		}
	
		public bool Exists(System.Int32 aRequestStatusId)
		{
			bool vResult;
				vResult = _Db.RequestStatuDb.Any(aRec => (aRec.RequestStatusId == aRequestStatusId));
			return vResult;
		}
	
		public RequestStatu Find(System.Int32 aRequestStatusId)
		{
			RequestStatu vResult;
			vResult = _Db.RequestStatuDb.Single(aRec => (aRec.RequestStatusId == aRequestStatusId));
			return vResult;
		}
	
		public RequestStatu Get(System.Int32 aRequestStatusId)
		{
			RequestStatu vResult;
			vResult = _Db.RequestStatuDb.FirstOrDefault(aRec => aRec.RequestStatusId == aRequestStatusId);
			return vResult;
		}
	
		public List<RequestStatu> GetAll()
		{
			List<RequestStatu> vResult;
			vResult = _Db.RequestStatuDb.ToList();
			return vResult;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public RequestStatu Add(RequestStatu aRequestStatu)
		{
			if (aRequestStatu == null)
			{
				throw new ArgumentNullException("aRequestStatu", " cannot be null!");
			}
	/*
			if (!aRequestStatu.IsRootEntity())
			{
				aRequestStatu.ClearToRootEntity();
			}
	*/
			if (!aRequestStatu.IsNew())
			{
				const string MESSAGE = 
					"RequestStatu Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
				aRequestStatu.AssignNewPK();
			aRequestStatu = _Db.RequestStatuDb.Add(aRequestStatu);
			_Db.SaveChanges();
			return aRequestStatu;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public void Insert(RequestStatu aRequestStatu)
		{
			if (aRequestStatu == null)
			{
				throw new ArgumentNullException("aRequestStatu", " cannot be null!");
			}
	/*
			if (!aRequestStatu.IsRootEntity())
			{
				aRequestStatu.ClearToRootEntity();
			}
	*/
			if (!aRequestStatu.IsNew())
			{
				const string MESSAGE = 
					"RequestStatu Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aRequestStatu.AssignNewPK();
			_Db.RequestStatuDb.Add(aRequestStatu);
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public System.Int32 InsertAndReturnPrimaryKey(RequestStatu aRequestStatu)
		{
			if (aRequestStatu == null)
			{
				throw new ArgumentNullException("aRequestStatu", " cannot be null!");
			}
	/*
			if (!aRequestStatu.IsRootEntity())
			{
				aRequestStatu.ClearToRootEntity();
			}
	*/
			if (!aRequestStatu.IsNew())
			{
				const string MESSAGE = 
					"RequestStatu Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aRequestStatu.AssignNewPK();
			aRequestStatu = _Db.RequestStatuDb.Add(aRequestStatu);
			_Db.SaveChanges();
			System.Int32 vResult = aRequestStatu.RequestStatusId;
			return vResult;
		}
	
		public void Update(RequestStatu aRequestStatu)
		{
			RequestStatu vRec = 
				_Db.RequestStatuDb.FirstOrDefault(aRec => aRec.RequestStatusId == aRequestStatu.RequestStatusId);
			vRec.AssignFromNoPrimaryKeys(aRequestStatu);
			_Db.SaveChanges();
		}
	
		public void Delete(System.Int32 aRequestStatusId)
		{
			RequestStatu vRec = 
				_Db.RequestStatuDb.FirstOrDefault(aRec => aRec.RequestStatusId == aRequestStatusId);
			if (vRec == null)
			{
				return; // Record is already gone, no worries!
			}
			_Db.RequestStatuDb.Remove(vRec);
			_Db.SaveChanges();
		}
	
	}
}
