//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	//using AWEFramework.AWECmn;
	//using Entity;
	using FbcBookIt.DataAccess;
	using FbcBookIt.Entity;
	
	// Table Name: School
	public partial interface ISchoolR
		: IBASE_RepositoryDbTable
	{
		bool Any();
	
		bool Exists(System.Guid aSchoolID);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		School Find(System.Guid aSchoolID);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		School Get(System.Guid aSchoolID);
	
		List<School> GetAll();
	
		// GetByActive will return the first occurrence of a record that
		// matches the criteria. If no record matches, the method will return null.
		School GetByActive(System.Boolean aActive);
	
			List<School> GetByActiveAsList(System.Boolean aActive);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		School Add(School aSchool);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		void Insert(School aSchool);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		System.Guid InsertAndReturnPrimaryKey(School aSchool);
	
		void Update(School aSchool);
	
		void Delete(System.Guid aSchoolID);
	
			void DeleteByActive(System.Boolean aActive);
	
		bool IsActive(System.Guid aSchoolID);
	
		void Remove(System.Guid aSchoolID);
	
		void Restore(System.Guid aSchoolID);
	
		void DeleteAllRemoved();
	
	}
	
	public partial class SchoolR
		: BASE_RepositoryDbTable, ISchoolR
	{
		public SchoolR
			(IBookInventoryContext aDb): base(aDb)
		{
		}
	
		public bool Any()
		{
			bool vResult;
			vResult = _Db.SchoolDb.Any();
			return vResult;
		}
	
		public bool Exists(System.Guid aSchoolID)
		{
			bool vResult;
				vResult = _Db.SchoolDb.Any(aRec => (aRec.SchoolID == aSchoolID));
			return vResult;
		}
	
		public School Find(System.Guid aSchoolID)
		{
			School vResult;
			vResult = _Db.SchoolDb.Single(aRec => (aRec.SchoolID == aSchoolID));
			return vResult;
		}
	
		public School Get(System.Guid aSchoolID)
		{
			School vResult;
			vResult = _Db.SchoolDb.FirstOrDefault(aRec => aRec.SchoolID == aSchoolID);
			return vResult;
		}
	
		public List<School> GetAll()
		{
			List<School> vResult;
			vResult = _Db.SchoolDb.ToList();
			return vResult;
		}
	
		public School GetByActive(System.Boolean aActive)
		{
			School vResult;
			vResult = 
				_Db.SchoolDb
					.Where(aRec => aRec.Active == aActive)
					.FirstOrDefault();
			return vResult;
		}
	
		public List<School> GetByActiveAsList(System.Boolean aActive)
		{
			List<School> vResult;
			vResult = 
				_Db.SchoolDb
					.Where(aRec => aRec.Active == aActive)
					.ToList();
			return vResult;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public School Add(School aSchool)
		{
			if (aSchool == null)
			{
				throw new ArgumentNullException("aSchool", " cannot be null!");
			}
	/*
			if (!aSchool.IsRootEntity())
			{
				aSchool.ClearToRootEntity();
			}
	*/
			if (!aSchool.IsNew())
			{
				const string MESSAGE = 
					"School Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
				aSchool.AssignNewPK();
			aSchool = _Db.SchoolDb.Add(aSchool);
			_Db.SaveChanges();
			return aSchool;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public void Insert(School aSchool)
		{
			if (aSchool == null)
			{
				throw new ArgumentNullException("aSchool", " cannot be null!");
			}
	/*
			if (!aSchool.IsRootEntity())
			{
				aSchool.ClearToRootEntity();
			}
	*/
			if (!aSchool.IsNew())
			{
				const string MESSAGE = 
					"School Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aSchool.AssignNewPK();
			_Db.SchoolDb.Add(aSchool);
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public System.Guid InsertAndReturnPrimaryKey(School aSchool)
		{
			if (aSchool == null)
			{
				throw new ArgumentNullException("aSchool", " cannot be null!");
			}
	/*
			if (!aSchool.IsRootEntity())
			{
				aSchool.ClearToRootEntity();
			}
	*/
			if (!aSchool.IsNew())
			{
				const string MESSAGE = 
					"School Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aSchool.AssignNewPK();
			aSchool = _Db.SchoolDb.Add(aSchool);
			_Db.SaveChanges();
			System.Guid vResult = aSchool.SchoolID;
			return vResult;
		}
	
		public void Update(School aSchool)
		{
			School vRec = 
				_Db.SchoolDb.FirstOrDefault(aRec => aRec.SchoolID == aSchool.SchoolID);
			vRec.AssignFromNoPrimaryKeys(aSchool);
			_Db.SaveChanges();
		}
	
		public void Delete(System.Guid aSchoolID)
		{
			School vRec = 
				_Db.SchoolDb.FirstOrDefault(aRec => aRec.SchoolID == aSchoolID);
			if (vRec == null)
			{
				return; // Record is already gone, no worries!
			}
			_Db.SchoolDb.Remove(vRec);
			_Db.SaveChanges();
		}
	
		public void DeleteByActive(System.Boolean aActive)
		{
				List<School> vListToDelete = 
					_Db.SchoolDb
						.Where(aRec => aRec.Active == aActive)
						.ToList();
				if (vListToDelete.Count < 1)
				{
					return;
				}
				foreach (School vRec in vListToDelete)
				{
					_Db.SchoolDb.Remove(vRec);
				}
				_Db.SaveChanges();
		}
	
		public bool IsActive(System.Guid aSchoolID)
		{
			School vRec = 
				_Db.SchoolDb.FirstOrDefault(aRec => aRec.SchoolID == aSchoolID);
			bool vResult = (vRec != null) && vRec.Active;
			return vResult;
		}
	
		public void Remove(System.Guid aSchoolID)
		{
			School vRec = 
				_Db.SchoolDb.FirstOrDefault(aRec => aRec.SchoolID == aSchoolID);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = false;
			_Db.SaveChanges();
		}
	
		public void Restore(System.Guid aSchoolID)
		{
			School vRec = 
				_Db.SchoolDb.FirstOrDefault(aRec => aRec.SchoolID == aSchoolID);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = true;
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Note that this method in EF is Really Ugly in that EF requires that 
		/// each record to be deleted must first be brought into the context, then 
		/// "removed", then SaveChanges called to actually delete the record(s).
		/// For a large number of records this gets memory intensive.
		/// </remark>
		public void DeleteAllRemoved()
		{
			List<School> vToDelete =
				_Db.SchoolDb
					.Where(aRec => !aRec.Active).ToList();
			if (vToDelete.Count < 1)
			{
				return;
			}
			foreach (School vRec in vToDelete)
			{
				_Db.SchoolDb.Remove(vRec);
			}
			_Db.SaveChanges();
		}
	
	}
}
