//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	//using AWEFramework.AWECmn;
	//using Entity;
	using FbcBookIt.DataAccess;
	using FbcBookIt.Entity;
	
	// Table Name: Teacher
	public partial interface ITeacherR
		: IBASE_RepositoryDbTable
	{
		bool Any();
	
		bool Exists(System.Guid aTeacherID);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		Teacher Find(System.Guid aTeacherID);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		Teacher Get(System.Guid aTeacherID);
	
		List<Teacher> GetAll();
	
		// GetByActive will return the first occurrence of a record that
		// matches the criteria. If no record matches, the method will return null.
		Teacher GetByActive(System.Boolean aActive);
	
			List<Teacher> GetByActiveAsList(System.Boolean aActive);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		Teacher Add(Teacher aTeacher);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		void Insert(Teacher aTeacher);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		System.Guid InsertAndReturnPrimaryKey(Teacher aTeacher);
	
		void Update(Teacher aTeacher);
	
		void Delete(System.Guid aTeacherID);
	
			void DeleteByActive(System.Boolean aActive);
	
		bool IsActive(System.Guid aTeacherID);
	
		void Remove(System.Guid aTeacherID);
	
		void Restore(System.Guid aTeacherID);
	
		void DeleteAllRemoved();
	
	}
	
	public partial class TeacherR
		: BASE_RepositoryDbTable, ITeacherR
	{
		public TeacherR
			(IBookInventoryContext aDb): base(aDb)
		{
		}
	
		public bool Any()
		{
			bool vResult;
			vResult = _Db.TeacherDb.Any();
			return vResult;
		}
	
		public bool Exists(System.Guid aTeacherID)
		{
			bool vResult;
				vResult = _Db.TeacherDb.Any(aRec => (aRec.TeacherID == aTeacherID));
			return vResult;
		}
	
		public Teacher Find(System.Guid aTeacherID)
		{
			Teacher vResult;
			vResult = _Db.TeacherDb.Single(aRec => (aRec.TeacherID == aTeacherID));
			return vResult;
		}
	
		public Teacher Get(System.Guid aTeacherID)
		{
			Teacher vResult;
			vResult = _Db.TeacherDb.FirstOrDefault(aRec => aRec.TeacherID == aTeacherID);
			return vResult;
		}
	
		public List<Teacher> GetAll()
		{
			List<Teacher> vResult;
			vResult = _Db.TeacherDb.ToList();
			return vResult;
		}
	
		public Teacher GetByActive(System.Boolean aActive)
		{
			Teacher vResult;
			vResult = 
				_Db.TeacherDb
					.Where(aRec => aRec.Active == aActive)
					.FirstOrDefault();
			return vResult;
		}
	
		public List<Teacher> GetByActiveAsList(System.Boolean aActive)
		{
			List<Teacher> vResult;
			vResult = 
				_Db.TeacherDb
					.Where(aRec => aRec.Active == aActive)
					.ToList();
			return vResult;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public Teacher Add(Teacher aTeacher)
		{
			if (aTeacher == null)
			{
				throw new ArgumentNullException("aTeacher", " cannot be null!");
			}
	/*
			if (!aTeacher.IsRootEntity())
			{
				aTeacher.ClearToRootEntity();
			}
	*/
			if (!aTeacher.IsNew())
			{
				const string MESSAGE = 
					"Teacher Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
				aTeacher.AssignNewPK();
			aTeacher = _Db.TeacherDb.Add(aTeacher);
			_Db.SaveChanges();
			return aTeacher;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public void Insert(Teacher aTeacher)
		{
			if (aTeacher == null)
			{
				throw new ArgumentNullException("aTeacher", " cannot be null!");
			}
	/*
			if (!aTeacher.IsRootEntity())
			{
				aTeacher.ClearToRootEntity();
			}
	*/
			if (!aTeacher.IsNew())
			{
				const string MESSAGE = 
					"Teacher Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aTeacher.AssignNewPK();
			_Db.TeacherDb.Add(aTeacher);
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public System.Guid InsertAndReturnPrimaryKey(Teacher aTeacher)
		{
			if (aTeacher == null)
			{
				throw new ArgumentNullException("aTeacher", " cannot be null!");
			}
	/*
			if (!aTeacher.IsRootEntity())
			{
				aTeacher.ClearToRootEntity();
			}
	*/
			if (!aTeacher.IsNew())
			{
				const string MESSAGE = 
					"Teacher Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aTeacher.AssignNewPK();
			aTeacher = _Db.TeacherDb.Add(aTeacher);
			_Db.SaveChanges();
			System.Guid vResult = aTeacher.TeacherID;
			return vResult;
		}
	
		public void Update(Teacher aTeacher)
		{
			Teacher vRec = 
				_Db.TeacherDb.FirstOrDefault(aRec => aRec.TeacherID == aTeacher.TeacherID);
			vRec.AssignFromNoPrimaryKeys(aTeacher);
			_Db.SaveChanges();
		}
	
		public void Delete(System.Guid aTeacherID)
		{
			Teacher vRec = 
				_Db.TeacherDb.FirstOrDefault(aRec => aRec.TeacherID == aTeacherID);
			if (vRec == null)
			{
				return; // Record is already gone, no worries!
			}
			_Db.TeacherDb.Remove(vRec);
			_Db.SaveChanges();
		}
	
		public void DeleteByActive(System.Boolean aActive)
		{
				List<Teacher> vListToDelete = 
					_Db.TeacherDb
						.Where(aRec => aRec.Active == aActive)
						.ToList();
				if (vListToDelete.Count < 1)
				{
					return;
				}
				foreach (Teacher vRec in vListToDelete)
				{
					_Db.TeacherDb.Remove(vRec);
				}
				_Db.SaveChanges();
		}
	
		public bool IsActive(System.Guid aTeacherID)
		{
			Teacher vRec = 
				_Db.TeacherDb.FirstOrDefault(aRec => aRec.TeacherID == aTeacherID);
			bool vResult = (vRec != null) && vRec.Active;
			return vResult;
		}
	
		public void Remove(System.Guid aTeacherID)
		{
			Teacher vRec = 
				_Db.TeacherDb.FirstOrDefault(aRec => aRec.TeacherID == aTeacherID);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = false;
			_Db.SaveChanges();
		}
	
		public void Restore(System.Guid aTeacherID)
		{
			Teacher vRec = 
				_Db.TeacherDb.FirstOrDefault(aRec => aRec.TeacherID == aTeacherID);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = true;
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Note that this method in EF is Really Ugly in that EF requires that 
		/// each record to be deleted must first be brought into the context, then 
		/// "removed", then SaveChanges called to actually delete the record(s).
		/// For a large number of records this gets memory intensive.
		/// </remark>
		public void DeleteAllRemoved()
		{
			List<Teacher> vToDelete =
				_Db.TeacherDb
					.Where(aRec => !aRec.Active).ToList();
			if (vToDelete.Count < 1)
			{
				return;
			}
			foreach (Teacher vRec in vToDelete)
			{
				_Db.TeacherDb.Remove(vRec);
			}
			_Db.SaveChanges();
		}
	
	}
}
