//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	//using AWEFramework.AWECmn;
	//using Entity;
	using FbcBookIt.DataAccess;
	using FbcBookIt.Entity;
	
	// Table Name: VolumeStatus
	public partial interface IVolumeStatusR
		: IBASE_RepositoryDbTable
	{
		bool Any();
	
		bool Exists(System.Int32 aVolumeStatusId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		VolumeStatus Find(System.Int32 aVolumeStatusId);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		VolumeStatus Get(System.Int32 aVolumeStatusId);
	
		List<VolumeStatus> GetAll();
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		VolumeStatus Add(VolumeStatus aVolumeStatus);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		void Insert(VolumeStatus aVolumeStatus);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		System.Int32 InsertAndReturnPrimaryKey(VolumeStatus aVolumeStatus);
	
		void Update(VolumeStatus aVolumeStatus);
	
		void Delete(System.Int32 aVolumeStatusId);
	
		bool IsActive(System.Int32 aVolumeStatusId);
	
		void Remove(System.Int32 aVolumeStatusId);
	
		void Restore(System.Int32 aVolumeStatusId);
	
		void DeleteAllRemoved();
	
	}
	
	public partial class VolumeStatusR
		: BASE_RepositoryDbTable, IVolumeStatusR
	{
		public VolumeStatusR
			(IBookInventoryContext aDb): base(aDb)
		{
		}
	
		public bool Any()
		{
			bool vResult;
			vResult = _Db.VolumeStatusDb.Any();
			return vResult;
		}
	
		public bool Exists(System.Int32 aVolumeStatusId)
		{
			bool vResult;
				vResult = _Db.VolumeStatusDb.Any(aRec => (aRec.VolumeStatusId == aVolumeStatusId));
			return vResult;
		}
	
		public VolumeStatus Find(System.Int32 aVolumeStatusId)
		{
			VolumeStatus vResult;
			vResult = _Db.VolumeStatusDb.Single(aRec => (aRec.VolumeStatusId == aVolumeStatusId));
			return vResult;
		}
	
		public VolumeStatus Get(System.Int32 aVolumeStatusId)
		{
			VolumeStatus vResult;
			vResult = _Db.VolumeStatusDb.FirstOrDefault(aRec => aRec.VolumeStatusId == aVolumeStatusId);
			return vResult;
		}
	
		public List<VolumeStatus> GetAll()
		{
			List<VolumeStatus> vResult;
			vResult = _Db.VolumeStatusDb.ToList();
			return vResult;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public VolumeStatus Add(VolumeStatus aVolumeStatus)
		{
			if (aVolumeStatus == null)
			{
				throw new ArgumentNullException("aVolumeStatus", " cannot be null!");
			}
	/*
			if (!aVolumeStatus.IsRootEntity())
			{
				aVolumeStatus.ClearToRootEntity();
			}
	*/
			if (!aVolumeStatus.IsNew())
			{
				const string MESSAGE = 
					"VolumeStatus Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
				aVolumeStatus.AssignNewPK();
			aVolumeStatus = _Db.VolumeStatusDb.Add(aVolumeStatus);
			_Db.SaveChanges();
			return aVolumeStatus;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public void Insert(VolumeStatus aVolumeStatus)
		{
			if (aVolumeStatus == null)
			{
				throw new ArgumentNullException("aVolumeStatus", " cannot be null!");
			}
	/*
			if (!aVolumeStatus.IsRootEntity())
			{
				aVolumeStatus.ClearToRootEntity();
			}
	*/
			if (!aVolumeStatus.IsNew())
			{
				const string MESSAGE = 
					"VolumeStatus Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aVolumeStatus.AssignNewPK();
			_Db.VolumeStatusDb.Add(aVolumeStatus);
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public System.Int32 InsertAndReturnPrimaryKey(VolumeStatus aVolumeStatus)
		{
			if (aVolumeStatus == null)
			{
				throw new ArgumentNullException("aVolumeStatus", " cannot be null!");
			}
	/*
			if (!aVolumeStatus.IsRootEntity())
			{
				aVolumeStatus.ClearToRootEntity();
			}
	*/
			if (!aVolumeStatus.IsNew())
			{
				const string MESSAGE = 
					"VolumeStatus Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aVolumeStatus.AssignNewPK();
			aVolumeStatus = _Db.VolumeStatusDb.Add(aVolumeStatus);
			_Db.SaveChanges();
			System.Int32 vResult = aVolumeStatus.VolumeStatusId;
			return vResult;
		}
	
		public void Update(VolumeStatus aVolumeStatus)
		{
			VolumeStatus vRec = 
				_Db.VolumeStatusDb.FirstOrDefault(aRec => aRec.VolumeStatusId == aVolumeStatus.VolumeStatusId);
			vRec.AssignFromNoPrimaryKeys(aVolumeStatus);
			_Db.SaveChanges();
		}
	
		public void Delete(System.Int32 aVolumeStatusId)
		{
			VolumeStatus vRec = 
				_Db.VolumeStatusDb.FirstOrDefault(aRec => aRec.VolumeStatusId == aVolumeStatusId);
			if (vRec == null)
			{
				return; // Record is already gone, no worries!
			}
			_Db.VolumeStatusDb.Remove(vRec);
			_Db.SaveChanges();
		}
	
		public bool IsActive(System.Int32 aVolumeStatusId)
		{
			VolumeStatus vRec = 
				_Db.VolumeStatusDb.FirstOrDefault(aRec => aRec.VolumeStatusId == aVolumeStatusId);
			bool vResult = (vRec != null) && vRec.Active;
			return vResult;
		}
	
		public void Remove(System.Int32 aVolumeStatusId)
		{
			VolumeStatus vRec = 
				_Db.VolumeStatusDb.FirstOrDefault(aRec => aRec.VolumeStatusId == aVolumeStatusId);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = false;
			_Db.SaveChanges();
		}
	
		public void Restore(System.Int32 aVolumeStatusId)
		{
			VolumeStatus vRec = 
				_Db.VolumeStatusDb.FirstOrDefault(aRec => aRec.VolumeStatusId == aVolumeStatusId);
			if (vRec == null)
			{
				return;
			}
			vRec.Active = true;
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Note that this method in EF is Really Ugly in that EF requires that 
		/// each record to be deleted must first be brought into the context, then 
		/// "removed", then SaveChanges called to actually delete the record(s).
		/// For a large number of records this gets memory intensive.
		/// </remark>
		public void DeleteAllRemoved()
		{
			List<VolumeStatus> vToDelete =
				_Db.VolumeStatusDb
					.Where(aRec => !aRec.Active).ToList();
			if (vToDelete.Count < 1)
			{
				return;
			}
			foreach (VolumeStatus vRec in vToDelete)
			{
				_Db.VolumeStatusDb.Remove(vRec);
			}
			_Db.SaveChanges();
		}
	
	}
}
