//-----------------------------------------------------------------------------
// <auto-generated> 
// ^^^ Comment out the above line to allow ReSharper to validate the 
//  using clauses.
//	This code was generated from a template.
//
//	Manual changes to this file may cause unexpected behavior in your 
//	application.
//	Manual changes to this file will be overwritten if the code is 
//	regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace FbcBookIt.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	//using AWEFramework.AWECmn;
	//using Entity;
	using FbcBookIt.DataAccess;
	using FbcBookIt.Entity;
	
	// Table Name: Volume
	public partial interface IVolumeR
		: IBASE_RepositoryDbTable
	{
		bool Any();
	
		bool Exists(System.Guid aVolumeID);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		Volume Find(System.Guid aVolumeID);
	
		// The only difference between "Find" and "Get" is that "Get" will return
		// a null if the record sought is not found whereas "Find" will throw
		// an exception.
		Volume Get(System.Guid aVolumeID);
	
		List<Volume> GetAll();
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		Volume Add(Volume aVolume);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		void Insert(Volume aVolume);
	
		// There are several methods that add a record to a table:
		//	1. Add
		//  2. Insert
		//  3. InsertAndReturnPrimaryKey
		// - Add will add the record if possible and return the entity updated with
		// the primary key information
		// - Insert will add the record if possible and return void.
		// - InsertAndReturnPrimaryKey will add the record if possible and then 
		// return the new primary key (a single value for single primary key
		// tables, an instance of a custom class containing all portions of the 
		// primary key for a table with a compound primary key).
		System.Guid InsertAndReturnPrimaryKey(Volume aVolume);
	
		void Update(Volume aVolume);
	
		void Delete(System.Guid aVolumeID);
	
	}
	
	public partial class VolumeR
		: BASE_RepositoryDbTable, IVolumeR
	{
		public VolumeR
			(IBookInventoryContext aDb): base(aDb)
		{
		}
	
		public bool Any()
		{
			bool vResult;
			vResult = _Db.VolumeDb.Any();
			return vResult;
		}
	
		public bool Exists(System.Guid aVolumeID)
		{
			bool vResult;
				vResult = _Db.VolumeDb.Any(aRec => (aRec.VolumeID == aVolumeID));
			return vResult;
		}
	
		public Volume Find(System.Guid aVolumeID)
		{
			Volume vResult;
			vResult = _Db.VolumeDb.Single(aRec => (aRec.VolumeID == aVolumeID));
			return vResult;
		}
	
		public Volume Get(System.Guid aVolumeID)
		{
			Volume vResult;
			vResult = _Db.VolumeDb.FirstOrDefault(aRec => aRec.VolumeID == aVolumeID);
			return vResult;
		}
	
		public List<Volume> GetAll()
		{
			List<Volume> vResult;
			vResult = _Db.VolumeDb.ToList();
			return vResult;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public Volume Add(Volume aVolume)
		{
			if (aVolume == null)
			{
				throw new ArgumentNullException("aVolume", " cannot be null!");
			}
	/*
			if (!aVolume.IsRootEntity())
			{
				aVolume.ClearToRootEntity();
			}
	*/
			if (!aVolume.IsNew())
			{
				const string MESSAGE = 
					"Volume Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
				aVolume.AssignNewPK();
			aVolume = _Db.VolumeDb.Add(aVolume);
			_Db.SaveChanges();
			return aVolume;
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public void Insert(Volume aVolume)
		{
			if (aVolume == null)
			{
				throw new ArgumentNullException("aVolume", " cannot be null!");
			}
	/*
			if (!aVolume.IsRootEntity())
			{
				aVolume.ClearToRootEntity();
			}
	*/
			if (!aVolume.IsNew())
			{
				const string MESSAGE = 
					"Volume Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aVolume.AssignNewPK();
			_Db.VolumeDb.Add(aVolume);
			_Db.SaveChanges();
		}
	
		/// <remark>
		/// Fragile:	This method presumes that any integer keys are
		///						auto-incrementing.
		/// </remark>
		public System.Guid InsertAndReturnPrimaryKey(Volume aVolume)
		{
			if (aVolume == null)
			{
				throw new ArgumentNullException("aVolume", " cannot be null!");
			}
	/*
			if (!aVolume.IsRootEntity())
			{
				aVolume.ClearToRootEntity();
			}
	*/
			if (!aVolume.IsNew())
			{
				const string MESSAGE = 
					"Volume Insert failed. Record has failed \"IsNew\" test.";
				throw new Exception(MESSAGE);
			}
			aVolume.AssignNewPK();
			aVolume = _Db.VolumeDb.Add(aVolume);
			_Db.SaveChanges();
			System.Guid vResult = aVolume.VolumeID;
			return vResult;
		}
	
		public void Update(Volume aVolume)
		{
			Volume vRec = 
				_Db.VolumeDb.FirstOrDefault(aRec => aRec.VolumeID == aVolume.VolumeID);
			vRec.AssignFromNoPrimaryKeys(aVolume);
			_Db.SaveChanges();
		}
	
		public void Delete(System.Guid aVolumeID)
		{
			Volume vRec = 
				_Db.VolumeDb.FirstOrDefault(aRec => aRec.VolumeID == aVolumeID);
			if (vRec == null)
			{
				return; // Record is already gone, no worries!
			}
			_Db.VolumeDb.Remove(vRec);
			_Db.SaveChanges();
		}
	
	}
}
